### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by Alabi12** [Alabi12/ruby-capstone#25]
[Link to the project](https://github.com/Alabi12/ruby-capstone/projects/1)

In this project we are two coding partners

Team #1 @Alabi12 
Team #2 @jonathanmunamire

_Kindly review the Kanban Board as per task is been shared._

**Comment by Whoistolu** [comment]
Hi Team,
@Alabi12 and @jonathanmunamire 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a Kanban setup, that does not have cards assigned to your 3rd partner due to her/his unavailability at the moment. However, kindly reach out to the Student Success team properly stating the whole issue and ensure you attach a screenshot of the feedback gotten from the student success team before asking for another review. I will also suggest that you two can start working on your cards upon waiting for a response from the SS team.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by FrederickMih** [comment]
## Hi 🙋 @Team , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights <img src = "https://media.giphy.com/media/3a53VvGpzUgh05qq7W/giphy.gif" width='30' ></img>


- Tasks are fairly distributed amongst team members ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
